apiVersion: v2
name: react-kub-app
description: A Helm chart for React Frontend and Node.js Backend application
type: application
version: 1.0.0
appVersion: "1.0"
keywords:
  - react
  - nodejs
  - express
maintainers:
  - name: Satishpanga
