apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: react-kub-app
  labels:
    app: backend
    tier: backend
spec:
  selector:
    app: backend
    tier: backend
  type: ClusterIP
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 5000
    name: http
