apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: react-kub-app
  labels:
    app: frontend
    tier: frontend
spec:
  selector:
    app: frontend
    tier: frontend
  type: LoadBalancer  # Change to NodePort for local/server
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
    name: http
    # nodePort: 30080  # Uncomment for NodePort
